version: "3.0"

services:
 apisevervice:
  build:
   context: ./app
  image: api-server:run
  environment:
  - TEST=http://localhost:3000/
  # volumes:
  # - ./testing/functional/keys.json:/app/keys/keys.json
  # depends_on:
  # - mockserver
  # - mockflask
  # ports:
  # - "8080:8080"
  # networks:
  # - apinet

 nginx:
  image: nginx:latest
  ports:
  - "8085:80"
  volumes:
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
  - apisevervice
  # networks:
  # - apinet

# networks:
#   apinet:
#     external:
#       name: apinet_network
